#! /bin/sh
wmname LG3D
sxhkd &
xsetroot -cursor_name left_ptr &
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          20

bspc config border_width         0
bspc config window_gap          10
bspc config focus_follows_pointer true
bspc click_to_focus any

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding		37

sxhkd &

#setting backgruond
nitrogen --restore &

xrdb .Xresources &


killall -q polybar
#while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
/home/alex/.config/polybar/launch.sh &

#set default cursor
xsetroot -cursor_name left_ptr &

#compositor
picom -b --config ~/.config/picom/picom.conf &

neofetch > ~/.cache/neofetch
